version: '3.8'

services:
  datastore:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - data_network
    environment:
      - MONGO_INITDB_DATABASE=social_media_analysis_db

  backend:
    build: .
    container_name: data_visualization_backend
    volumes:
      - ./backend:/app/backend
      - ./src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - datastore
    networks:
      - data_network
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://datastore:27017/

  frontend:
    build: .
    container_name: data_visualization_frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - data_network
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

  data_ingestion:
    build: .
    container_name: data_ingestion_service
    volumes:
      - ./src:/app/src
    depends_on:
      - datastore
    networks:
      - data_network
    environment:
      - MONGODB_URI=mongodb://datastore:27017/
    command: python src/data_ingest.py

networks:
  data_network:
    driver: bridge

volumes:
  mongo_data: